apiVersion: v1
kind: Secret
metadata:
  name: epackbook-secret
  namespace: epackbook
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: epackbook
  DB_PORT: "5432"
  DB_HOST: epackbook-postgres
